/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResidentRouteImport } from './routes/resident'
import { Route as WatchmanRouteImport } from './routes/watchman'
import { Route as ResidentIndexRouteImport } from './routes/resident.index'
import { Route as ResidentMaintenanceRouteImport } from './routes/resident.maintenance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentRoute = ResidentRouteImport.update({
  id: '/resident',
  path: '/resident',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchmanRoute = WatchmanRouteImport.update({
  id: '/watchman',
  path: '/watchman',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentIndexRoute = ResidentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResidentRoute,
} as any)
const ResidentMaintenanceRoute = ResidentMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => ResidentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/resident': typeof ResidentRouteWithChildren
  '/watchman': typeof WatchmanRoute
  '/resident/maintenance': typeof ResidentMaintenanceRoute
  '/resident/': typeof ResidentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/watchman': typeof WatchmanRoute
  '/resident/maintenance': typeof ResidentMaintenanceRoute
  '/resident': typeof ResidentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/resident': typeof ResidentRouteWithChildren
  '/watchman': typeof WatchmanRoute
  '/resident/maintenance': typeof ResidentMaintenanceRoute
  '/resident/': typeof ResidentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/resident'
    | '/watchman'
    | '/resident/maintenance'
    | '/resident/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/watchman'
    | '/resident/maintenance'
    | '/resident'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/resident'
    | '/watchman'
    | '/resident/maintenance'
    | '/resident/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ResidentRoute: typeof ResidentRouteWithChildren
  WatchmanRoute: typeof WatchmanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident': {
      id: '/resident'
      path: '/resident'
      fullPath: '/resident'
      preLoaderRoute: typeof ResidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchman': {
      id: '/watchman'
      path: '/watchman'
      fullPath: '/watchman'
      preLoaderRoute: typeof WatchmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resident/': {
      id: '/resident/'
      path: '/'
      fullPath: '/resident/'
      preLoaderRoute: typeof ResidentIndexRouteImport
      parentRoute: typeof ResidentRoute
    }
    '/resident/maintenance': {
      id: '/resident/maintenance'
      path: '/maintenance'
      fullPath: '/resident/maintenance'
      preLoaderRoute: typeof ResidentMaintenanceRouteImport
      parentRoute: typeof ResidentRoute
    }
  }
}

interface ResidentRouteChildren {
  ResidentMaintenanceRoute: typeof ResidentMaintenanceRoute
  ResidentIndexRoute: typeof ResidentIndexRoute
}

const ResidentRouteChildren: ResidentRouteChildren = {
  ResidentMaintenanceRoute: ResidentMaintenanceRoute,
  ResidentIndexRoute: ResidentIndexRoute,
}

const ResidentRouteWithChildren = ResidentRoute._addFileChildren(
  ResidentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ResidentRoute: ResidentRouteWithChildren,
  WatchmanRoute: WatchmanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
